// <auto-generated />
namespace Treasury7MD.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TreasuryDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TreasuryDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201701021542518_TreasuryDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
